### ISSUE TITLE
Have you ever tried Frama-C 20.0

### ISSUE THREAD

**Issue by aogrcs** [Frama-C/Frama-C-snapshot#35] opened 2020-01-16 09:42 UTC
I used Ubuntu 18.04.3 LTS for x86_64, opam 2.0.5, ocaml 4.05.0, why3 1.2.0, I found those problems:
1 Must install num, but it needs ocaml > 4.05
2 Which version of Coq should be used?
Could anyone can give some help? Thanks

**Comment by maroneze** [comment] 2020-01-16 10:43
There is unfortunately an issue with the `num` package in OCaml 4.05 (https://github.com/ocaml/opam-repository/issues/15441) and some specific versions of ocamlfind. For instance, ocamlfind 1.8.0 should work, ocamlfind 1.8.1 will not. If this is your ocamlfind version, you should normally be able to downgrade it to 1.8.0 without many issues. Note that `num` does not *require* OCaml > 4.05, it's just that the "pseudo-package" available in 4.05 has some quirks which cause issues with ocamlfind (at least that's how it's supposed to work, if there are no other issues we are unaware of).

Coq is officially deprecated in Frama-C 20 (hence why it is no longer listed on the [known working configuration](https://github.com/Frama-C/Frama-C-snapshot/blob/master/INSTALL.md#known-working-configuration)), but it should still work, roughly versions between 8.7 and 8.10.

**Comment by aogrcs** [comment] 2020-01-17 01:57
"Coq is officially deprecated" means that Frama-C 20 uses why3 instead of Coq? Thanks

**Comment by AllanBlanchard** [comment] 2020-01-17 10:30
In Frama-C 20, the default backend of WP for discharging the proof obligations is Why3. Native backends to Alt-Ergo and Coq are still there but deprecated as indicated in : http://frama-c.com/Changelog.html#Calcium-20.0 .

**Comment by maroneze** [comment] 2020-04-28 11:48
It seems the issue is no longer active, so I'm closing it. If you have other issues just tell us.

**Closed by maroneze** 2020-04-28 11:48 UTC
