### ISSUE TITLE
opam install frama-c on mac

### ISSUE THREAD

**Issue by aogrcs** [Frama-C/Frama-C-snapshot#7] opened 2018-04-22 14:24 UTC
There is the error as following

```
:=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[frama-c] /Users/wenlongxie/Downloads/TOOLS/ already up-to-date
The following actions will be performed:
  ∗  install frama-c 20171101*
       Coq can be used with the WP plug-in for proving interactively proof obligations

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[frama-c.20171101] /Users/wenlongxie/Downloads/TOOLS/ already up-to-date

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[ERROR] The compilation of frama-c failed at "sh -eux ./run_autoconf_if_needed.sh".
Processing  1/1: [frama-c: rm]
#=== ERROR while installing frama-c.20171101 ==================================#
# opam-version 1.2.2
# os           darwin
# command      sh -eux ./run_autoconf_if_needed.sh
# path         /Users/wenlongxie/.opam/4.05.0/build/frama-c.20171101
# compiler     4.05.0
# exit-code    1
# env-file     /Users/wenlongxie/.opam/4.05.0/build/frama-c.20171101/frama-c-1443-05296d.env
# stdout-file  /Users/wenlongxie/.opam/4.05.0/build/frama-c.20171101/frama-c-1443-05296d.out
# stderr-file  /Users/wenlongxie/.opam/4.05.0/build/frama-c.20171101/frama-c-1443-05296d.err
### stderr ###
# + '[' '!' -f configure ']'
# + autoconf
# autoconf: error: no input file



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions failed
  ∗  install frama-c 20171101
No changes have been performed
```

Maybe it was caused by opam pin add --kind=path frama-c <dir>, I'm a little confused, thanks
Sincerely

**Comment by maroneze** [comment] 2018-04-22 21:56
Yes, it's likely the `opam pin` was the cause. What happens is that Frama-C requires `autoconf` when in pinned mode to generate a fresh `configure` script for its installation. This is not necessary when doing a standard `opam install frama-c` since the .tar.gz in the opam package already contains a `./configure`, but on a non-standard setting, it is necessary to generate a new one, which requires `autoconf`.

Still, it's very odd that opam does not report an issue with `autoconf`, since Frama-C clearly depends on `conf-autoconf`. Could you please report the exact Mac OS version you are using, and the output of `opam info conf-autoconf`?

Seeing that the opam package reports `osx` and `homebrew`, and you have `darwin`, it *might* be an issue in that package. You could eventually try installing some other package that requires it (e.g. `alt-ergo`) and see if the same error occurs. If so, then we have a likely culprit.

**Comment by aogrcs** [comment] 2018-04-23 15:25
My os version is 10.13.4, and the output of opam info conf-autoconf is:

package: conf-autoconf
             version: 0.1
          repository: default
            homepage: http://www.gnu.org/software/autoconf
         bug-reports: https://github.com/ocaml/opam-repository/issues
            dev-repo: https://github.com/ocaml/opam-repository.git
              author: https://www.gnu.org/software/autoconf/autoconf.html#maintainer
             license: GPL-3.0
             depends: conf-which
   installed-version: 0.1 [system 4.05.0]
   available-version: 0.1
         description: Virtual package relying on autoconf installation.
This package can only install if the autoconf command
is available on the system.

the output of opam install altgr-ergo is:

[NOTE] Package altgr-ergo is already installed (current version is 1.30).

**Comment by maroneze** [comment] 2018-04-23 16:53
Sorry, I misread the error message, `autoconf` is indeed installed and not the cause.

I've been able to obtain your error message when accidentally **http**-pinning frama-c to `https://github.com/Frama-C/Frama-C-snapshot` instead of **git**-pinning it to `https://github.com/Frama-C/Frama-C-snapshot.git`. However, if I download the Frama-C .tar.gz and then **path**-pin it with `opam pin add --kind=path frama-c .` (note the "current working directory" `.` at the end of the command), it does work for me.

Could you please detail all the steps you used to get Frama-C locally, then pin it? opam sometimes gets confused when there are leftover files from previous installations and/or uninstallations, so it's not easy to reproduce the exact errors. Running some aggressive deletion commands such as `find ~/.opam/4.05.0/ -iname "*frama-c*" -exec rm -rf {} \;` might help cleaning it, even though it should not be necessary.

Note that a beta release of the new Frama-C 17 (Chlorine) has just been made available on the [Frama-C Github wiki](https://github.com/Frama-C/Frama-C-snapshot/wiki/Frama-C-Chlorine-20180501-beta), and I was able to install it with:

    opam pin add frama-c "https://github.com/Frama-C/Frama-C-snapshot.git#release-candidates"

However some colleagues are having issues similar to yours with opam, so we're trying to understand exactly which configurations are causing problems.

**Comment by aogrcs** [comment] 2018-04-24 15:31
Hi,
First I tried to install frame-c following:
http://frama-c.com/install-sulfur-20171101.html#installing-frama-c-from-opam
I did all:
opam install depext
opam depext frama-c
opam install --deps-only frama-c
But it did not support the ocaml version 4.06 and I tried opam switch 4.05.0, they all worked except the last opam pin add --kind=path frama-c <dir>

Second I tried:
http://frama-c.com/install-sulfur-20171101.html#installing-frama-c-on-mac-os-x
all steps worked except the last one opam install frama-c

I also removed the frama-c dir in 4.05.0/build, did not work yet

Thanks, sincerely

**Comment by maroneze** [comment] 2018-04-24 17:01
I'm sorry, I'm unable to reproduce it, the only way I get your error message is if I deliberately remove `configure.in` from the directory where the Frama-C .tar.gz was extracted.

Still, since you were able to install all of Frama-C's dependencies, at this point you can let go of opam and compile Frama-C's sources directly. The opam-based instructions are shorter and easier when everything works, but if things go wrong, then the most reliable way is to compile it yourself:

```
./configure
make -j
make install
```

This will require superuser permissions to install Frama-C in /usr/local/bin.

Optionally, you can use `./configure --prefix=<absolute path to a directory in your PATH>` if you prefer to install it somewhere else.

**Comment by aogrcs** [comment] 2018-04-27 14:44
Hi, the following operation
opam pin add frama-c "git://github.com/Frama-C/Frama-C-snapshot.git#release-candidates"
did work, and I succeed to install frama-c 17.
Should I close this or wait someone to reproduce it? Thanks!
Sincerely

**Comment by maroneze** [comment] 2018-04-27 17:08
Great!

I honestly don't see why it didn't work before, but if `git://` works for you, that's good to know! I'll consider suggesting that next time if someone has similar issues.

I think it's better to close it for now, and if someone manages to reproduce it someday, or have the same issue, then reopen and see from there.

**Closed by maroneze** 2018-04-27 17:08 UTC
